server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - AuthenticationFilter
      
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**
        filters:
        - AuthenticationFilter
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
        filters:
        - AuthenticationFilter
        
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/authecation/**
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Okta configuration for api gateway
#okta:
#  oauth2:
#    issuer: https://dev-21933278.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oa8fs7ix2tO4OUXy5d7
#    client-secret: 7PCFPViPulLgUwYu82wjr__Tl9MJkgGLGGo6NKht
#    scopes: openid, profile, email, offline_access